In [ ]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [1]:
import numpy as np
l=[0,1,2,3,4,5]
arr=np.array(l)
arr
print("Datatype:",arr.dtype)

Datatype: int64


In [2]:
#2. Given a NumPy array 'arr', check if its data type is float64.

In [3]:
arr = np.array([1.5, 2.6, 3.7])
print("array",arr)
print("Datatype:",arr.dtype)
arr.dtype

array [1.5 2.6 3.7]
Datatype: float64


dtype('float64')

In [4]:
#3.. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [5]:
complex_list = [3 + 4j, 5 + 7j, -2 - 1j]
np_array = np.array(complex_list)
print(np_array)
np_array.dtype

[ 3.+4.j  5.+7.j -2.-1.j]


dtype('complex128')

In [6]:
#4.Convert an existing NumPy array 'arr' of integers to float32 data type

In [7]:
import numpy as np
arr=np.array([1,4,5,6,7,8])
print("Datatype of arr:", arr.dtype)
arr=arr.astype('float32')
print("Datatype of new arr:", arr.dtype)

Datatype of arr: int64
Datatype of new arr: float32


In [8]:
 #5.Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [9]:
arr=np.array([500.0,34.2,67.2,23.0,87.1])
print("Array:",arr)
print ("Datatype of arr:", arr.dtype)
arr=arr.astype('float32')
print("Datatype of arr after conversion:", arr.dtype)

Array: [500.   34.2  67.2  23.   87.1]
Datatype of arr: float64
Datatype of arr after conversion: float32


In [10]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype.

In [11]:
array_attributes=np.array([[2,4,5],[6,7,8]])
print("array_attributes:",array_attributes)
#Shape of array
print("Shape of array:", array_attributes.shape)
print("Size of array:", array_attributes.size)
print("Datatype of array:", array_attributes.dtype)

array_attributes: [[2 4 5]
 [6 7 8]]
Shape of array: (2, 3)
Size of array: 6
Datatype of array: int64


In [12]:
 #7.Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [13]:
arr=np.array([[2,4,5],[6,7,8]])
print("Array:",arr)
print("Array dimension:",arr.ndim)

Array: [[2 4 5]
 [6 7 8]]
Array dimension: 2


In [14]:
#8.Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [15]:
arr=np.array([[2,4,5],[6,7,8]])
print("Item_size:",arr.size)
print("Size of each byte:",arr.itemsize)
print("Total size in bytes:",((arr.size)*(arr.itemsize)))

Item_size: 6
Size of each byte: 8
Total size in bytes: 48


In [16]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [17]:
arr=np.array([[2,4,5],[6,7,8]])
arr.strides

(24, 8)

In [18]:
#10.Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [19]:
arr=np.array([[2,4,5],[6,7,8]])
d=arr.strides

In [20]:
#11.Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of z

In [21]:
n=int(input("Enter a number of your choice:"))
arr=np.zeros(n)
arr

Enter a number of your choice: 5


array([0., 0., 0., 0., 0.])

In [22]:
#12.Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [23]:
rows=int(input("Enter rows:"))
cols=int(input("Enter cols:"))
np.ones((rows,cols))

Enter rows: 8
Enter cols: 6


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
#13.Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

In [25]:
import numpy as np
generate_range_array=np.arange(1,20,3)
print("generate_range_array:", generate_range_array)

generate_range_array: [ 1  4  7 10 13 16 19]


In [26]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

In [27]:
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
generate_linear_space(1.0,20.0,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [28]:
#15.Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

In [29]:
n=int(input("Please enter a number:"))
np.eye(n)

Please enter a number: 5


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
#16.Write a function that takes a Python list and converts it into a NumPy array.

In [31]:
l=[2,3,4,8,5,6]
print("Type of 'l':", type(l))
arr=np.array(l)
print("Numpy array:", arr)

Type of 'l': <class 'list'>
Numpy array: [2 3 4 8 5 6]


In [32]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [34]:
l=[200,45,67,86,98,32]
arr=np.array(l)
print("Array is:", arr)
arr1=arr.view()
arr1
arr[0]=1000
arr
print("Array:", arr)
print("Array with view:", arr1)

Array is: [200  45  67  86  98  32]
Array: [1000   45   67   86   98   32]
Array with view: [1000   45   67   86   98   32]


In [35]:
#18.Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [36]:
arr1=np.array([[1,3,5],[5,6,7]])
arr2=np.array([[7,5,4],[8,7,2]])
print("Array1:", arr1)
print("Array2:", arr2)
conc_matrix=np.concatenate((arr1,arr2),axis=0)
print("Concatenated matrix is:", conc_matrix)

Array1: [[1 3 5]
 [5 6 7]]
Array2: [[7 5 4]
 [8 7 2]]
Concatenated matrix is: [[1 3 5]
 [5 6 7]
 [7 5 4]
 [8 7 2]]


In [37]:
#19.Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [38]:
arr1=np.array([[2,3,4],[5,6,7]])
arr2=np.array([[2,3],[5,6]])
print("Array1:", arr1)
print("Array2:", arr2)
conc_matrix=np.concatenate((arr1,arr2),axis=1)
print("Concatenate matrix is:", conc_matrix)

Array1: [[2 3 4]
 [5 6 7]]
Array2: [[2 3]
 [5 6]]
Concatenate matrix is: [[2 3 4 2 3]
 [5 6 7 5 6]]


In [39]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [40]:
arr1=np.array([[1,2,3,4],[5,6,3,2]])
arr2=np.array([[6,7,8,9],[1,2,3,4]])
arr3=np.array([[3,6,7,8],[4,8,9,5]])
stc_mat=np.vstack((arr1,arr2,arr3))
print(stc_mat)

[[1 2 3 4]
 [5 6 3 2]
 [6 7 8 9]
 [1 2 3 4]
 [3 6 7 8]
 [4 8 9 5]]


In [41]:
#21.Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [42]:
import numpy as np
array=np.arange(30,81,3)
array

array([30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78])

In [43]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [44]:
arr1=np.linspace(0,1,10)
print(arr1)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [45]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [46]:
import numpy as np
def logarithmically_spaced_values():
    return np.logspace(start=np.log10(1), stop=np.log10(1000), num=5)
result = logarithmically_spaced_values()
print("Logarithmic values b/w 1 & 1000 are:", result)

Logarithmic values b/w 1 & 1000 are: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [47]:
#24. . Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [48]:
import pandas as pd
data_array = np.random.randint(1,101,(5, 3))
print("data_array:", data_array)
df=pd.DataFrame(data_array)
print("DataFrame:", df)

data_array: [[40 35 56]
 [58 79 78]
 [59 78 33]
 [58 42 59]
 [53 83 39]]
DataFrame:     0   1   2
0  40  35  56
1  58  79  78
2  59  78  33
3  58  42  59
4  53  83  39


In [49]:
#25.Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [50]:
import pandas as pd
data = {'A': [-1, 20, -13, 4, -5],
        'B': [10, 20, 130, -40, 50]}
df=pd.DataFrame(data)
print("DataFrame:", df)
df[df['A']<0]=0
print(df)

DataFrame:     A    B
0  -1   10
1  20   20
2 -13  130
3   4  -40
4  -5   50
    A   B
0   0   0
1  20  20
2   0   0
3   4 -40
4   0   0


In [51]:
#26.Access the 3rd element from the given NumPy array.arr = np.array([10, 20, 30, 40, 50])

In [52]:
arr = np.array([10, 20, 30, 40, 50])
arr[3]

40

In [53]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.

In [54]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[[1,2]]

array([[4, 5, 6],
       [7, 8, 9]])

In [55]:
#28.Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [56]:
arr = np.array([3, 8, 2, 10, 5, 7]) #given
print("Elements greater than 5 are:", arr>5)

Elements greater than 5 are: [False  True False  True False  True]


In [57]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array

In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) #given
arr[2:6]

array([3, 4, 5, 6])

In [59]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [60]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [61]:
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [62]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [63]:
def extract_elements_by_indices(arr, indices):
    return arr[np.unravel_index(indices, arr.shape)]
arr = np.array([[1, 20, 3],
                [14, 5, 60],
                [7, 88, 90]])

indices = np.array([4, 0, 2, 1, 5, 8, 6, 3, 7])  # Example indices for extraction

result = extract_elements_by_indices(arr, indices)
print("Extracted elements based on indices:")
print(result)

Extracted elements based on indices:
[ 5  1  3 20 60 90  7 14 88]


In [64]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [65]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
boolean_indexing=array1>5
print("Boolean Indexing as:", boolean_indexing)

Boolean Indexing as: [False False False False False  True  True  True  True  True]


In [66]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [67]:
arr = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[10, 11, 12],[13, 14, 15],[16, 17, 18]],[[19, 20, 21],[22, 23, 24],[25, 26, 27]]])
def extract_elements(arr, indices_dim1, indices_dim2, indices_dim3):
    return arr[indices_dim1, indices_dim2, indices_dim3]
indices_dim1 = np.array([0, 1, 2])
indices_dim2 = np.array([1, 2, 0])
indices_dim3 = np.array([2, 0, 1])
result = extract_elements(arr, indices_dim1, indices_dim2, indices_dim3)
print("Extracted elements:")
print(result)

Extracted elements:
[ 6 16 20]


In [68]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [69]:
def elements_satisfying_conditions(arr, condition1, condition2):
    return arr[(condition1) & (condition2)]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition1 = arr > 2
condition2 = arr < 8
result = elements_satisfying_conditions(arr, condition1, condition2)
print("Elements satisfying both conditions:")
print(result)

Elements satisfying both conditions:
[3 4 5 6 7]


In [70]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [71]:
def extract_elements_2d(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

result = extract_elements_2d(arr, row_indices, col_indices)
print("Extracted elements:")
print(result)

Extracted elements:
[2 6 7]


In [72]:
#36.Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [73]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr+5

array([[[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])

In [74]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [75]:
arr1=np.random.randint(1,10,(1,3))
arr2=np.random.randint(1,20,(3,4))
print("Array-1:", arr1)
print("Array-2:", arr2)
print("Matrix multiplications is:", np.dot(arr1,arr2))

Array-1: [[9 8 9]]
Array-2: [[13  4  4 19]
 [16  3  3  8]
 [15  4  3  2]]
Matrix multiplications is: [[380  96  87 253]]


In [76]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting

In [78]:
arr1=np.array([[1, 2, 3, 4]])
arr2=np.array([[5, 6, 7],[8, 9, 10],[11, 12, 13],[14, 15, 16]]) 
print("Array1:", arr1)
print("Array2:",arr2)
arr1.T
Addition_matrix=arr1.T+arr2
print("Addition of matrix is:", Addition_matrix)

Array1: [[1 2 3 4]]
Array2: [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]
Addition of matrix is: [[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [79]:
#39.Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy  broadcasting

In [80]:
import numpy as np
arr1=np.random.randint(1,10,(3,1))
arr2=np.random.randint(1,10,(1,3))
print("Array1:", arr1)
print("Array2:",arr2)
result=arr1+arr2
print("Addition of arrays:", result)

Array1: [[5]
 [9]
 [4]]
Array2: [[1 1 2]]
Addition of arrays: [[ 6  6  7]
 [10 10 11]
 [ 5  5  6]]


In [81]:
#40.Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [82]:
arr1=np.random.randint(1,10,(2,3))
arr2=np.random.randint(1,10,(2,2))
print("Array1:",arr1)
print("Array2:",arr2)
arr2_reshaped = arr2.reshape(2, 1, 2)
result = arr1.T * arr2_reshaped
print("Result of multiplication using broadcasting:")
print("Matrix multiplication is:", result)

Array1: [[4 1 3]
 [9 9 8]]
Array2: [[8 3]
 [9 7]]
Result of multiplication using broadcasting:
Matrix multiplication is: [[[32 27]
  [ 8 27]
  [24 24]]

 [[36 63]
  [ 9 63]
  [27 56]]]


In [84]:
#41. Calculate column-wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [85]:
column_mean=np.mean(arr, axis=0)
print("Column mean:", column_mean)

Column mean: [2.5 3.5 4.5]


In [86]:
#42.Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [87]:
Row_maxvalue=np.max(arr, axis=1)
print("Row wise max value:", Row_maxvalue)

Row wise max value: [3 6]


In [88]:
#43.For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [89]:
column_max_indices = np.argmax(arr, axis=0)
print("Indices of maximum value in each column:", column_max_indices)

Indices of maximum value in each column: [1 1 1]


In [90]:
#44.For the given array, apply custom function to calculate moving sum along rows
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [91]:
def moving_sum(row):
    return np.cumsum(row)

arr = np.array([[1, 2, 3], [4, 5, 6]])
moving_sum_result = np.apply_along_axis(moving_sum, axis=1, arr=arr)
print("Moving sum along rows:")
print(moving_sum_result)

Moving sum along rows:
[[ 1  3  6]
 [ 4  9 15]]


In [92]:
#45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])

In [93]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
are_all_even = np.all(arr % 2 == 0, axis=0)
print(are_all_even)

[False False False]


In [94]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

In [95]:
Res_array=original_array.reshape(2,3)
print("Reshaped array:", Res_array)
original_array1=Res_array.base
print("Original_array:", original_array1)

Reshaped array: [[1 2 3]
 [4 5 6]]
Original_array: [1 2 3 4 5 6]


In [96]:
#47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [97]:
 print("Flattened matrix:", input_matrix.flatten())

Flattened matrix: [1 2 3 4 5 6]


In [98]:
#48. Write a function that concatenates two given arrays along a specified axis.
import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [99]:
concatenated_arrays=np.concatenate((array1,array2),axis=1)
print("Concatenated arrays are:", concatenated_arrays)

Concatenated arrays are: [[1 2 5 6]
 [3 4 7 8]]


In [100]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [101]:
import numpy as np
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_arrays = np.split(original_array,3, axis=0)
print("Split arrays along axis 0:")
for arr in split_arrays:
    print(arr)

Split arrays along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [102]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

In [103]:
def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    for idx, value in zip([2, 4], [10, 11]):
        original_array = np.insert(original_array, idx, value)
    original_array = np.delete(original_array, [1, 3])
    return original_array

In [104]:
#51.  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [105]:
arr1=np.random.randint(1,20,(3,3))
arr2=np.random.randint(1,10,(3,3))
print ("Array1:", arr1)
print ("Array2:", arr2)
print("Addition of array:", np.add(arr1,arr2))

Array1: [[11 13  6]
 [ 6  1 17]
 [13  8  2]]
Array2: [[2 8 7]
 [1 2 4]
 [4 4 6]]
Addition of array: [[13 21 13]
 [ 7  3 21]
 [17 12  8]]


In [108]:
#52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [109]:
arr1=np.array([[10,9,8,7,6],[5,4,3,2,1]])
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array 1 is:", arr1)
print("Array 2 is:", arr2)
sub_value=np.subtract(arr1,arr2)
print("Subtracted value:", sub_value)

Array 1 is: [[10  9  8  7  6]
 [ 5  4  3  2  1]]
Array 2 is: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Subtracted value: [[ 9  7  5  3  1]
 [-1 -3 -5 -7 -9]]


In [110]:
#53. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2

In [111]:
arr1=np.array([8,9,7,2,7])
arr2=np.array([1,2,3,4,5])
print("Array1:", arr1)
print("Array2:", arr2)
multiplication_matrix=np.dot(arr1,arr2)
print("Multiplication of array:",multiplication_matrix)

Array1: [8 9 7 2 7]
Array2: [1 2 3 4 5]
Multiplication of array: 90


In [112]:
#54.Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1  to 5. Perform element-wise division of `arr1` by `arr2`.

In [114]:
arr1=np.arange(2,11,2)
arr2=np.arange(1,6,1)
print("Array1:", arr1)
print("Array2:", arr2)
print("Element wise division:", arr1/arr2)

Array1: [ 2  4  6  8 10]
Array2: [1 2 3 4 5]
Element wise division: [2. 2. 2. 2. 2.]


In [115]:
#55.Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [116]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,4,3,2,1])
print("Array1:", arr1)
print("Array2:", arr2)

Array1: [1 2 3 4 5]
Array2: [5 4 3 2 1]


In [117]:
Exponentiation=np.power(arr1,arr2)
print("Element wise exponentiation:", Exponentiation)

Element wise exponentiation: [ 1 16 27 16  5]


In [118]:
#56.Write a function that counts the occurrences of a specific substring within a NumPy array of strings
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [119]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
def count_substring_occurrences(arr, substring):
    count = 0
    for string in arr:
        count += string.count(substring)
    return count
occurrences = count_substring_occurrences(arr, substring)
print("Occurrences of substring '{}' in the array: {}".format(substring, occurrences))

Occurrences of substring 'hello' in the array: 3


In [120]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.
import numpy as np
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [121]:
np.char.upper(arr)

array(['HELLO', 'WORLD', 'OPENAI', 'GPT'], dtype='<U6')

In [122]:
#58.Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [123]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def replace_substring(arr, old_substring, new_substring):
    replaced_arr = np.char.replace(arr, old_substring, new_substring)
    return replaced_arr
old_substring = 'apple'
new_substring = 'orange'

result = replace_substring(arr, old_substring, new_substring)
print(result)

['orange' 'banana' 'grape' 'pineorange']


In [124]:
 #59. Write a function that concatenates strings in a NumPy array element-wise.

In [125]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI']) #given

In [126]:
print(arr1)
print(arr2)
array=np.concatenate([arr1,arr2],axis=0)

['Hello' 'World']
['Open' 'AI']


In [127]:
array

array(['Hello', 'World', 'Open', 'AI'], dtype='<U5')

In [128]:
#60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [129]:
print("Original string:", arr)
res=max(arr,key=len)
print("Longest string:", res)

Original string: ['apple' 'banana' 'grape' 'pineapple']
Longest string: pineapple


In [130]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and  standard deviation of the dataset using NumPy's functions.

In [131]:
dataset = np.random.randint(1, 1001, size=100)
print (dataset)

[841 763 803  84 315 113 518 234 967 990 617 360 998 437 116 672 708 361
 711  84 366 846 241 839 859 723 912 584 390  41 899 805 213 202 492 216
 181  68 598 992 294 854 814 222 969 902 198 235 206  94 290 938 503 551
  99 841 541 373 593 122 148  53 580 991 215 685 612 634 662 406 769  92
 115 322 145 172 236 861 143 276 809 112 117  39 847 344 592 803 776 904
 834  72 850 138 672 725 542  49 282 783]


In [132]:
print("Mean of the dataset:", np.mean(dataset))
print("Median of the dataset:", np.median(dataset))
print("Standard deviation of the dataset:", np.std(dataset))
print("Variance of the dataset:", np.var(dataset))

Mean of the dataset: 492.05
Median of the dataset: 510.5
Standard deviation of the dataset: 308.1843725758981
Variance of the dataset: 94977.60749999998


In [133]:
#62.Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [134]:
dataset=np.random.randint(1,101,size=50)
print("Dataset:", dataset)
percentile_25th = np.percentile(dataset, 25)
percentile_75th = np.percentile(dataset, 75)
print("25th Percentile:", percentile_25th)
print("75th Percentile:", percentile_75th)

Dataset: [73 81 54 60 67 76 16 13 40 47 21 45 43 90 57 31 38  9 29 35  5 83 87 23
 81 19 24 99 28 79 94 84 98 24 26 86 73 20 12 49 54  7 91 80 88 51 18 70
 66 76]
25th Percentile: 24.5
75th Percentile: 79.75


In [135]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function

In [136]:
set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([2, 4, 6, 8, 10])
correlation_coefficient = np.corrcoef(set1, set2)[0, 1]

print("Correlation Coefficient:", correlation_coefficient)

Correlation Coefficient: 0.9999999999999999


In [137]:
#64.  Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [138]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))
print("Array1:", arr1)
print("Array2:", arr2)
print("Multiplication of matrix:", np.dot(arr1,arr2))

Array1: [[1 2 1]
 [2 1 2]
 [1 1 2]]
Array2: [[2 1 2]
 [2 1 2]
 [1 2 1]]
Multiplication of matrix: [[7 5 7]
 [8 7 8]
 [6 6 6]]


In [139]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles

In [192]:
import numpy as np
dataset=np.random.randint(10,1001,size=50)
print("Dataset:", dataset)

Dataset: [909 482 460 391 623 649 121 589 287 754 670 605 764 651 527 517 296 282
 969 234 101 496 691 567 515 556 855 379 852 120 870 429 598 202 822  25
 758 445 130 197 204 792 403 493  72 404 164  92 388 102]


In [193]:
percentiles = np.percentile(arr, [10, 25, 50, 75, 90])
print("10th percentile:", percentiles[0])
print("25th percentile (first quartile):", percentiles[1])
print("Median (50th percentile):", percentiles[2])
print("75th percentile (third quartile):", percentiles[3])
print("90th percentile:", percentiles[4])

10th percentile: 1.2
25th percentile (first quartile): 1.5
Median (50th percentile): 2.0
75th percentile (third quartile): 2.5
90th percentile: 2.8


In [147]:
#66. Create a NumPy array of integers and find the index of a specific element.

In [148]:
arr=np.array([5,1,52,41,23,8,7])
element_to_find=41
index = np.where(arr == element_to_find)
print("Array:", arr)
print("Index of", element_to_find, ":", index[0])

Array: [ 5  1 52 41 23  8  7]
Index of 41 : [3]


In [149]:
#67. Generate a random NumPy array and sort it in ascending order.

In [150]:
array=np.random.randint(1,10,(2,3))
print("The required array is:", array)
print("The sorted array is:", np.sort(array))
array
np.sort(array)

The required array is: [[3 5 8]
 [7 2 3]]
The sorted array is: [[3 5 8]
 [2 3 7]]


array([[3, 5, 8],
       [2, 3, 7]])

In [151]:
#68.  Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

In [152]:
arr>20

array([False,  True, False,  True, False,  True])

In [153]:
#69.Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])

In [154]:
print("Elements divisible by 3 are:", arr%3==0)


Elements divisible by 3 are: [False False False  True  True]


In [155]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

In [156]:
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print("Filtered array:", filtered_arr)

Filtered array: [20 30 40]


In [157]:
#71.For the given NumPy array, check its byte order using the `dtype` attribute byteorder
import numpy as np
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print("Byte order:", byte_order)

Byte order: =


In [158]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [159]:
arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

In [160]:
#73.  For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [161]:
arr_swapped = arr.newbyteorder()

print("Original array:", arr)
print("Array with swapped byte order:", arr_swapped)

Original array: [1 2 3]
Array with swapped byte order: [16777216 33554432 50331648]


In [162]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [163]:
import numpy as np
import sys
system_byteorder = sys.byteorder
if system_byteorder == 'little':
    arr_swapped = arr.newbyteorder('big')
else:
    arr_swapped = arr.newbyteorder('little')

print("Original array:", arr)
print("Array with swapped byte order based on system endianness:", arr_swapped)

Original array: [1 2 3]
Array with swapped byte order based on system endianness: [16777216 33554432 50331648]


In [164]:
#75.  For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [165]:
dtype_byteorder = arr.dtype.byteorder
system_byteorder = np.dtype(np.int32).byteorder
byte_swapping_needed = dtype_byteorder != system_byteorder

if byte_swapping_needed:
    print("Byte swapping is necessary for current system.")
else:
    print("Byte swapping is not necessary for current system.")

Byte swapping is not necessary for current system.


In [166]:
#76.Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [167]:
arr1=np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [168]:
copy_arr=arr1.copy()
print("copy_array:", copy_arr)

copy_array: [ 1  2  3  4  5  6  7  8  9 10]


In [169]:
copy_arr[5]=500
print("Modified array:" ,copy_arr)
print("Original array:", arr1)

Modified array: [  1   2   3   4   5 500   7   8   9  10]
Original array: [ 1  2  3  4  5  6  7  8  9 10]


In [170]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [171]:
matrix=np.random.randint(1,3,(3,3,))
print("Matrix is:", matrix)
view_slice=matrix[0:2,0:2]
print("Slice matrix:", view_slice)
view_slice[0][1]=100
print("Modified slice matrix:", view_slice)
print("Original matrix:", matrix)

Matrix is: [[2 1 2]
 [1 1 1]
 [1 1 2]]
Slice matrix: [[2 1]
 [1 1]]
Modified slice matrix: [[  2 100]
 [  1   1]]
Original matrix: [[  2 100   2]
 [  1   1   1]
 [  1   1   2]]


In [172]:
#78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a

In [173]:
array_a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("Original array_a:", array_a)
view_b=array_a[0:2][1:2]
print("view_b:", view_b)
new_array=view_b+5
print("New array after broadcasting 5 to view_b:", new_array)
print("Original array_a", array_a)

Original array_a: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
view_b: [[4 5 6]]
New array after broadcasting 5 to view_b: [[ 9 10 11]]
Original array_a [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [174]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [175]:
orig_array=np.array([[1,2,3,4],[5,6,7,8]])
print("Original array:", orig_array)
d=orig_array.reshape(4,2)
print ("Reshaped array view:", d)
d[2][1]=1000
print("Reshaped array view after slicing:", d)
print("Original array:", orig_array)

Original array: [[1 2 3 4]
 [5 6 7 8]]
Reshaped array view: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Reshaped array view after slicing: [[   1    2]
 [   3    4]
 [   5 1000]
 [   7    8]]
Original array: [[   1    2    3    4]
 [   5 1000    7    8]]


In [176]:
#80.Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [177]:
data=np.random.randint(1,20,(3,4))
print(data)

[[ 9 14  5  6]
 [10 18  9  5]
 [14  8  7 18]]


In [178]:
data_copy=data.copy()>5
print(data_copy)

[[ True  True False  True]
 [ True  True  True False]
 [ True  True  True  True]]


In [179]:
print("Copied data data_copy:", data_copy)

Copied data data_copy: [[ True  True False  True]
 [ True  True  True False]
 [ True  True  True  True]]


In [180]:
data_copy[1][1]=200
print("Modified data is:", data_copy)
print("Original data is:", data)

Modified data is: [[ True  True False  True]
 [ True  True  True False]
 [ True  True  True  True]]
Original data is: [[ 9 14  5  6]
 [10 18  9  5]
 [14  8  7 18]]


In [181]:
#81.Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [182]:
A=np.random.randint(1,3,(3,3))
B=np.random.randint(1,3,(3,3))
print(A)
print(B)
print("Addition of A & B:", A+B)
print("Substraction of A & B:", A-B)

[[2 2 2]
 [2 1 1]
 [1 1 2]]
[[1 2 1]
 [2 1 2]
 [1 1 1]]
Addition of A & B: [[3 4 3]
 [4 2 3]
 [2 2 3]]
Substraction of A & B: [[ 1  0  1]
 [ 0  0 -1]
 [ 0  0  1]]


In [183]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [184]:
C=np.random.randint(2,3,(3,2))
D=np.random.randint(2,4,(2,4))
print(C)
print(D)
np.dot(C,D)

[[2 2]
 [2 2]
 [2 2]]
[[3 3 2 2]
 [2 3 3 3]]


array([[10, 12, 10, 10],
       [10, 12, 10, 10],
       [10, 12, 10, 10]])

In [185]:
 #83. Create a matrix `E` and find its transpose.

In [186]:
D=np.random.randint(2,4,(2,4))
print ("Matrix:", D)
print("Transpose Matrix:", D.T)

Matrix: [[2 2 3 3]
 [3 2 3 3]]
Transpose Matrix: [[2 3]
 [2 2]
 [3 3]
 [3 3]]


In [187]:
#84.Generate a square matrix `F` and compute its determinant.

In [188]:
F=np.array([[6, 1, 1],[4, -2, 5],[2, 8, 7]])
print("Square matrix 'F':", F)
det = np.linalg.det(F)
print("Determinant of matrix 'F':", det)

Square matrix 'F': [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
Determinant of matrix 'F': -306.0


In [190]:
#85.Create a square matrix `G` and find its inverse.

In [191]:
G=np.array([[6, 1, 1],[4, -2, 5],[2, 8, 7]])
print ("Matrix 'G':", G)
print("Inverse of matrix 'G':", np.linalg.inv(G))

Matrix 'G': [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
Inverse of matrix 'G': [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
